// Generated by gencpp from file grasp_demo/CamToReal.msg
// DO NOT EDIT!


#ifndef GRASP_DEMO_MESSAGE_CAMTOREAL_H
#define GRASP_DEMO_MESSAGE_CAMTOREAL_H

#include <ros/service_traits.h>


#include <grasp_demo/CamToRealRequest.h>
#include <grasp_demo/CamToRealResponse.h>


namespace grasp_demo
{

struct CamToReal
{

typedef CamToRealRequest Request;
typedef CamToRealResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CamToReal
} // namespace grasp_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grasp_demo::CamToReal > {
  static const char* value()
  {
    return "189ac79be7b27a6947e618b03843336a";
  }

  static const char* value(const ::grasp_demo::CamToReal&) { return value(); }
};

template<>
struct DataType< ::grasp_demo::CamToReal > {
  static const char* value()
  {
    return "grasp_demo/CamToReal";
  }

  static const char* value(const ::grasp_demo::CamToReal&) { return value(); }
};


// service_traits::MD5Sum< ::grasp_demo::CamToRealRequest> should match
// service_traits::MD5Sum< ::grasp_demo::CamToReal >
template<>
struct MD5Sum< ::grasp_demo::CamToRealRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_demo::CamToReal >::value();
  }
  static const char* value(const ::grasp_demo::CamToRealRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_demo::CamToRealRequest> should match
// service_traits::DataType< ::grasp_demo::CamToReal >
template<>
struct DataType< ::grasp_demo::CamToRealRequest>
{
  static const char* value()
  {
    return DataType< ::grasp_demo::CamToReal >::value();
  }
  static const char* value(const ::grasp_demo::CamToRealRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grasp_demo::CamToRealResponse> should match
// service_traits::MD5Sum< ::grasp_demo::CamToReal >
template<>
struct MD5Sum< ::grasp_demo::CamToRealResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_demo::CamToReal >::value();
  }
  static const char* value(const ::grasp_demo::CamToRealResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_demo::CamToRealResponse> should match
// service_traits::DataType< ::grasp_demo::CamToReal >
template<>
struct DataType< ::grasp_demo::CamToRealResponse>
{
  static const char* value()
  {
    return DataType< ::grasp_demo::CamToReal >::value();
  }
  static const char* value(const ::grasp_demo::CamToRealResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASP_DEMO_MESSAGE_CAMTOREAL_H
