// Generated by gencpp from file grasp_demo/GripperMove.msg
// DO NOT EDIT!


#ifndef GRASP_DEMO_MESSAGE_GRIPPERMOVE_H
#define GRASP_DEMO_MESSAGE_GRIPPERMOVE_H

#include <ros/service_traits.h>


#include <grasp_demo/GripperMoveRequest.h>
#include <grasp_demo/GripperMoveResponse.h>


namespace grasp_demo
{

struct GripperMove
{

typedef GripperMoveRequest Request;
typedef GripperMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperMove
} // namespace grasp_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grasp_demo::GripperMove > {
  static const char* value()
  {
    return "bfc68b580573d62fc32a37a0f2f5f368";
  }

  static const char* value(const ::grasp_demo::GripperMove&) { return value(); }
};

template<>
struct DataType< ::grasp_demo::GripperMove > {
  static const char* value()
  {
    return "grasp_demo/GripperMove";
  }

  static const char* value(const ::grasp_demo::GripperMove&) { return value(); }
};


// service_traits::MD5Sum< ::grasp_demo::GripperMoveRequest> should match
// service_traits::MD5Sum< ::grasp_demo::GripperMove >
template<>
struct MD5Sum< ::grasp_demo::GripperMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_demo::GripperMove >::value();
  }
  static const char* value(const ::grasp_demo::GripperMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_demo::GripperMoveRequest> should match
// service_traits::DataType< ::grasp_demo::GripperMove >
template<>
struct DataType< ::grasp_demo::GripperMoveRequest>
{
  static const char* value()
  {
    return DataType< ::grasp_demo::GripperMove >::value();
  }
  static const char* value(const ::grasp_demo::GripperMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grasp_demo::GripperMoveResponse> should match
// service_traits::MD5Sum< ::grasp_demo::GripperMove >
template<>
struct MD5Sum< ::grasp_demo::GripperMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_demo::GripperMove >::value();
  }
  static const char* value(const ::grasp_demo::GripperMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_demo::GripperMoveResponse> should match
// service_traits::DataType< ::grasp_demo::GripperMove >
template<>
struct DataType< ::grasp_demo::GripperMoveResponse>
{
  static const char* value()
  {
    return DataType< ::grasp_demo::GripperMove >::value();
  }
  static const char* value(const ::grasp_demo::GripperMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASP_DEMO_MESSAGE_GRIPPERMOVE_H
