// Generated by gencpp from file grasp_demo/GripperMoveRequest.msg
// DO NOT EDIT!


#ifndef GRASP_DEMO_MESSAGE_GRIPPERMOVEREQUEST_H
#define GRASP_DEMO_MESSAGE_GRIPPERMOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_demo
{
template <class ContainerAllocator>
struct GripperMoveRequest_
{
  typedef GripperMoveRequest_<ContainerAllocator> Type;

  GripperMoveRequest_()
    : pulse(0.0)  {
    }
  GripperMoveRequest_(const ContainerAllocator& _alloc)
    : pulse(0.0)  {
  (void)_alloc;
    }



   typedef double _pulse_type;
  _pulse_type pulse;





  typedef boost::shared_ptr< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GripperMoveRequest_

typedef ::grasp_demo::GripperMoveRequest_<std::allocator<void> > GripperMoveRequest;

typedef boost::shared_ptr< ::grasp_demo::GripperMoveRequest > GripperMoveRequestPtr;
typedef boost::shared_ptr< ::grasp_demo::GripperMoveRequest const> GripperMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_demo::GripperMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasp_demo::GripperMoveRequest_<ContainerAllocator1> & lhs, const ::grasp_demo::GripperMoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pulse == rhs.pulse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasp_demo::GripperMoveRequest_<ContainerAllocator1> & lhs, const ::grasp_demo::GripperMoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasp_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bc125a2a5574ebd1d47acd40c278d61";
  }

  static const char* value(const ::grasp_demo::GripperMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bc125a2a5574ebdULL;
  static const uint64_t static_value2 = 0x1d47acd40c278d61ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_demo/GripperMoveRequest";
  }

  static const char* value(const ::grasp_demo::GripperMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pulse\n"
;
  }

  static const char* value(const ::grasp_demo::GripperMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pulse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_demo::GripperMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_demo::GripperMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "pulse: ";
    Printer<double>::stream(s, indent + "  ", v.pulse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_DEMO_MESSAGE_GRIPPERMOVEREQUEST_H
