// Generated by gencpp from file grasp_demo/SpawnObjRequest.msg
// DO NOT EDIT!


#ifndef GRASP_DEMO_MESSAGE_SPAWNOBJREQUEST_H
#define GRASP_DEMO_MESSAGE_SPAWNOBJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_demo
{
template <class ContainerAllocator>
struct SpawnObjRequest_
{
  typedef SpawnObjRequest_<ContainerAllocator> Type;

  SpawnObjRequest_()
    : type(0)  {
    }
  SpawnObjRequest_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpawnObjRequest_

typedef ::grasp_demo::SpawnObjRequest_<std::allocator<void> > SpawnObjRequest;

typedef boost::shared_ptr< ::grasp_demo::SpawnObjRequest > SpawnObjRequestPtr;
typedef boost::shared_ptr< ::grasp_demo::SpawnObjRequest const> SpawnObjRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_demo::SpawnObjRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasp_demo::SpawnObjRequest_<ContainerAllocator1> & lhs, const ::grasp_demo::SpawnObjRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasp_demo::SpawnObjRequest_<ContainerAllocator1> & lhs, const ::grasp_demo::SpawnObjRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasp_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3958533281df6e9cc0a725a386f3b5df";
  }

  static const char* value(const ::grasp_demo::SpawnObjRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3958533281df6e9cULL;
  static const uint64_t static_value2 = 0xc0a725a386f3b5dfULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_demo/SpawnObjRequest";
  }

  static const char* value(const ::grasp_demo::SpawnObjRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 type\n"
;
  }

  static const char* value(const ::grasp_demo::SpawnObjRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpawnObjRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_demo::SpawnObjRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_demo::SpawnObjRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_DEMO_MESSAGE_SPAWNOBJREQUEST_H
