(cl:defpackage grasp_demo-srv
  (:use )
  (:export
   "CAMTOREAL"
   "<CAMTOREAL-REQUEST>"
   "CAMTOREAL-REQUEST"
   "<CAMTOREAL-RESPONSE>"
   "CAMTOREAL-RESPONSE"
   "GRIPPERMOVE"
   "<GRIPPERMOVE-REQUEST>"
   "GRIPPERMOVE-REQUEST"
   "<GRIPPERMOVE-RESPONSE>"
   "GRIPPERMOVE-RESPONSE"
   "SPAWNOBJ"
   "<SPAWNOBJ-REQUEST>"
   "SPAWNOBJ-REQUEST"
   "<SPAWNOBJ-RESPONSE>"
   "SPAWNOBJ-RESPONSE"
  ))

